# Generated by Django 2.2.14 on 2020-10-02 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('name_eng', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='image/avatar')),
                ('intro', models.TextField(null=True)),
                ('education', models.CharField(blank=True, max_length=20, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company', models.CharField(max_length=30)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('favorite_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('specialty', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('award', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(max_length=30)),
                ('tool_list', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.profile',),
        ),
    ]
