# Generated by Django 2.2.14 on 2020-10-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='u_type',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
