# Generated by Django 2.2.14 on 2020-09-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200928_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('age', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('nickname', models.CharField(max_length=10, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='image/avatar')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('intro', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
