# Generated by Django 2.2.14 on 2020-09-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200928_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Profile')),
                ('awards', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.profile',),
        ),
    ]
