# Generated by Django 2.2.14 on 2020-11-29 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'director'), (2, 'actor'), (3, 'staff'), (4, 'movie')])),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Director')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
