# Generated by Django 3.1.3 on 2020-11-30 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_phone_number'),
        ('accounts', '0015_auto_20201130_2209'),
    ]

    operations = [
    ]
