# Generated by Django 2.2.14 on 2020-09-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='content_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='section',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
