# Generated by Django 2.2.14 on 2020-09-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200927_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='APortfolio',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Portfolio')),
            ],
            bases=('main.portfolio',),
        ),
        migrations.CreateModel(
            name='DPortfolio',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Portfolio')),
            ],
            bases=('main.portfolio',),
        ),
        migrations.CreateModel(
            name='SPortfolio',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Portfolio')),
            ],
            bases=('main.portfolio',),
        ),
    ]
