# Generated by Django 2.2.14 on 2020-10-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201006_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
