# Generated by Django 2.2.14 on 2020-11-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_filmography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='uid',
            new_name='director',
        ),
    ]
