# Generated by Django 3.1.3 on 2020-11-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201112_0207'),
        ('main', '0007_auto_20201113_1531'),
    ]

    operations = [
    ]
