# Generated by Django 2.2.14 on 2020-11-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201113_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('액션', '액션'), ('범죄', '범죄'), ('SF', 'SF'), ('코미디', '코미디'), ('스릴러', '스릴러'), ('전쟁', '전쟁'), ('스포츠', '스포츠'), ('판타지', '판타지'), ('음악', '음악'), ('멜로', '멜로')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_thumbnail',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sportfolio',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
