# Generated by Django 2.2.14 on 2020-11-29 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20201126_0350'),
        ('main', '0008_auto_20201114_2202'),
    ]

    operations = [
    ]
